sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gx+CbaJgBM1lXf6lzTanK9OKzIG0O4RPBbVpwtHhz/GLV7m5U2KagoPbbbs6A+nRHPoJtwV6289frCUxNlR7njv6BwOShMehvmyrtKdpWy90uVK72zfM47A5/Xvecq7UmPTxsPJoyzLheiOougVvxBEerqunA3ih9/3SSsMqQciMfgMHmgscd1MUVgjU0QBBjPjruEeaf79mIPt+NQSajgWSlt4LpvzvofAyzedf8P0hezp451ih7+iw4X7fS1zdjbKi0+WmA3zfmhv6waEuDKsTp7M5b6L23JQv7+EurgBGDpX2/4rol1koHfKvvMcC2U0RHUzsVn0/L3uj9B/oy9vjv0+Jn38mbpmlO2JfwWi9FdhcGq95mnrbxGuDIORRjzjErHXJzl3up5ohGRodjNkXWJCDbPydZqtr+cNSBE3px3fuKv19jx1BxfrDeHQK+s5Gmr64vfrDLUt/Fhx3GyoEgl2RLFRwI7AYTttOQ13x0RRuCJt9O+ii376nHZk9Brzjte67NorLNUOkvnu9HxUhpuXXwjl3HKrXBD5mTadp4HrIxNrAqjoJmfh9jM0mNrv2ZhhdbDKCc5nRKIMg1kHg9LtJl2MH2yeFMpFZw4emmwyCM78KQ7Tlk+/nx4oHhNUtDfJo5ISHFUlg6eXxLb42+x1okliwZCxsE/zLSJs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/-Captains-Courageous---A-Story-of-the-Grand-Banks_2186
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy